/**
 * Shared project data — single source of truth for index.html (chat) and projects.html
 * Edit this file to update project cards across all pages.
 */
const PROJECTS = [
  {
    url: 'projects/setupguide.html',
    img: 'images/13.jpg',
    company: 'Meta · WhatsApp',
    title: 'Onboarding for WhatsApp Partner Platforms',
    summary: 'Landed a new product leading to +9% onboarding completion and +19.7% revenue.',
    filters: ['business', 'developer', 'framework', 'funnel'],
  },
  {
    url: 'projects/ig-inbox.html',
    img: 'images/2025_4.jpg',
    company: 'Meta · Instagram',
    title: 'Modular System for Instagram Inbox Tools',
    summary: 'Defined framework across 5 tools to increase business adoption.',
    filters: ['business', 'framework'],
  },
  {
    url: 'projects/template-tool.html',
    img: 'images/2025_3.jpg',
    company: 'Meta · WhatsApp',
    title: 'Modular System for Template Creation Tools',
    summary: 'Defined framework for 7+ creation flows with 1.6x completion rates.',
    filters: ['business', 'developer'],
  },
  {
    url: '',
    img: 'images/2025_6.jpg',
    company: 'Meta · WhatsApp',
    title: 'Onboarding for WhatsApp API Integration',
    summary: 'Streamlined API onboarding to help developers integrate WhatsApp faster.',
    filters: ['business', 'developer', 'funnel'],
    comingSoon: true,
  },
  {
    url: '',
    img: 'images/2025_5.jpg',
    company: 'Meta · Business Inbox',
    title: 'Meta Business Inbox Growth',
    summary: 'Designed and shipped a new bulk messaging tool for businesses at scale.',
    filters: ['business', 'monetization'],
    comingSoon: true,
  },
  {
    url: 'https://www.facebook.com/business/ads/click-to-message-ads',
    img: 'images/2025_2.jpg',
    company: 'Meta · Ads Manager',
    title: 'Ad Creation Improvement for WhatsApp Ads',
    summary: 'Built solutions on a legacy ad tool to unlock $XM annual revenue.',
    filters: ['monetization'],
    external: true,
  },
  {
    url: 'https://business.google.com/us/google-ads/?pli=1',
    img: 'images/10.jpg',
    company: 'Google · Search Ads',
    title: 'Search Ads Growth',
    summary: 'Grew Google Search ad products with new product lines or optimized experiences.',
    filters: ['monetization', 'funnel'],
    external: true,
  },
  {
    url: 'projects/maryland-portal-discovery.html',
    img: 'images/12.jpg',
    company: 'Enovational · Gov UX',
    title: 'Maryland DNR License Portal',
    summary: 'Shaped strategy + design for government portal redesign with CEO support.',
    filters: ['consumer'],
  },
  {
    url: 'projects/theme-editor.html',
    img: 'images/02.jpg',
    company: 'ASUS · ZenUI',
    title: 'Theme Online Editor',
    summary: 'Built 0-1 web tool to reduce 50% of mobile GUI theme creation steps.',
    filters: ['consumer'],
  },
  {
    url: 'projects/gmail.html',
    img: 'images/04.jpg',
    company: 'Side Project',
    title: 'Gmail for Personal',
    summary: 'Redesigned Gmail to better serve personal use cases and daily needs.',
    filters: ['consumer'],
  },
  {
    url: 'projects/hygge.html',
    img: 'images/01.jpg',
    company: 'Side Project',
    title: 'Hygge Trip Planner',
    summary: 'All-in-one trip planner app integrating multiple services and personalization.',
    filters: ['consumer'],
  },
  {
    url: 'projects/theme-packs.html',
    img: 'images/07.jpg',
    company: 'ASUS · ZenUI',
    title: 'Theme Packs',
    summary: 'Multiple theme pack designs created for ASUS ZenUI users.',
    filters: ['consumer'],
  },
  {
    url: 'projects/goose.html',
    img: 'images/09.jpg',
    company: 'Side Project',
    title: 'Geese',
    summary: 'Illustration project presenting a creative mythology narrative about geese.',
    filters: ['consumer'],
  },
];
